version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: audit_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Almaty
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build: .
    container_name: audit_backend
    restart: always
    depends_on:
      - db
    env_file:
      - .env

volumes:
  pgdata: